# Git Account
git_url: "github.com/Muhammad-Rizal-Supriadi/BC_Intelijen.git"
git_branch: "master"
git_msg: "update files with ansible"
git_username: Muhammad-Rizal-Supriadi
git_email: mrsupriadi2000@gmail.com
git_password: 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
