---
- name: Deploy Fabric CA services
  hosts: peer1
  gather_facts: false

  tasks:
    - name: Create network
      docker_network:
        name: fabric_test

    - name: Deploy ca orderer service
      docker_container:
        name: ca_orderer.zillabc.io
        image: hyperledger/fabric-ca
        env:
          FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
          FABRIC_CA_SERVER_CA_NAME: ca-orderer
          FABRIC_CA_SERVER_TLS_ENABLED: "true"
          FABRIC_CA_SERVER_PORT: "9054"
        ports:
          - "9054:9054"
        command: "sh -c 'fabric-ca-server start -b admin:adminpw -d'"
        volumes:
          - "./{{ project_name }}/Fabric/ca/fabric-ca/ordererKpu:/etc/hyperledger/fabric-ca-server"
        networks:
          - name: fabric_test
            aliases:
              - ca_orderer.zillabc.io

    - name: Deploy ca kpu service
      docker_container:
        name: ca.kpu.zillabc.io
        image: hyperledger/fabric-ca
        env:
          FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
          FABRIC_CA_SERVER_CA_NAME: ca.kpu.zillabc.io
          FABRIC_CA_SERVER_TLS_ENABLED: "true"
          FABRIC_CA_SERVER_PORT: "7054"
        ports:
          - "7054:7054"
        command: "sh -c 'fabric-ca-server start -b admin:adminpw -d'"
        volumes:
          - "./{{ project_name }}/Fabric/ca/fabric-ca/kpu:/etc/hyperledger/fabric-ca-server"
        networks:
          - name: fabric_test
            aliases:
              - ca.kpu.zillabc.io
        hostname: ca.kpu.zillabc.io
