---
# tasks file for nodejs
- name: Install nodejs gnupg
  tags: nodejs, install, setup
  apt:
    name: gnupg
    update_cache: yes
    state: present

- name: Install the gpg key for nodejs
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Remove conflicting package libnode72
  apt:
    name: libnode72
    state: absent

- name: Install the nodejs repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x focal main"
    state: present
    update_cache: yes

- name: Install NodeJS
  tags: nodejs, install
  apt:
    name: nodejs
    state: present

- name: Check Node version
  become: false
  shell: node -v
  register: node_version_output

- name: Display Node version
  debug:
    var: node_version_output.stdout