---
# tasks file for python
- name: Update local repository list
  apt:
    update_cache: yes

- name: Install python supporting dependencies
  apt:
    name:
      - build-essential
      - zlib1g-dev
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - wget
    state: present

- name: Create python source directory
  file:
    path: /python
    state: directory

- name: Download python source code
  get_url:
    url: https://www.python.org/ftp/python/3.11.0/Python-3.11.0a7.tgz
    dest: /python/Python-3.11.0a7.tgz

- name: Extract python source code
  command: tar -xvf /python/Python-3.11.0a7.tgz
  args:
    chdir: /python

- name: Configure python
  command: ./configure --enable-optimizations
  args:
    chdir: /python/Python-3.11.0a7

- name: Build and install python
  command: make install
  args:
    chdir: /python/Python-3.11.0a7

- name: Check python version
  command: python3 --version
  register: python3_version

- name: Display python version
  debug:
    var: python3_version.stdout


- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install docker and docker-compose package
  pip:
    name: 
      - docker
      - docker-compose
    executable: pip
    state: present

- name: Check python package
  shell: pip list | grep -F 'docker'
  register: python3_package

- name: Display python package
  debug:
    var: python3_package.stdout