---
- name: Set fact with incremented peer value
  set_fact:
    peer: "{{ groups['peer'].index(inventory_hostname) + 1 }}"

- name: Debug peer value
  debug:
    var: hostvars[inventory_hostname]['peer']

- name: Peer deploy chaincode militer
  shell: "{{ chaincode_path }}/deployChaincode.sh {{ hostvars[inventory_hostname]['peer'] }} {{ militer_divisi }} {{ channel_name }}"
  args:
    chdir: "{{ chaincode_path }}"
    executable: /bin/bash
