---
#tasks file for chaincode
- name: Create File Deploy Chaincode
  template:
    src: templates/deployChaincode.sh.j2
    dest: "{{ chaincode_path }}/deployChaincode.sh"

- include_tasks: "install-chaincode.yml"

- name: Pause for 7 seconds
  pause:
    seconds: 7

- include_tasks: deploy-chaincode.yml