---
- name: Fix Docker APT Conflict
  hosts: vmhost
  become: true
  tasks:
    - name: Remove conflicting Docker keyring
      shell: sudo rm -f /etc/apt/trusted.gpg.d/docker.gpg
      ignore_errors: true

    - name: Remove conflicting Docker sources.list entry
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb.*https:\/\/download.docker.com\/linux\/ubuntu.*focal.*$'
        state: absent
      ignore_errors: true

    - name: Add Docker repository
      shell: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/docker.list
      changed_when: false

    - name: Clean APT cache
      apt:
        autoclean: yes

    - name: Update APT cache
      apt:
        update_cache: yes
